### ISSUE TITLE
Firefox can't open ALMA pipeline files

### ISSUE THREAD

**Issue by brianmajor** [opencadc/arcade#11]
Viewing ALMA pipeline qa files (.html files intended to be viewed in a web browser) causes firefox to crash frequently

**Comment by brianmajor** [comment]
Firefox does not seem to like being run as a container in arcade.  I suggest have a few common utilities be hosted in the noVNC container instead.  The two which are best candidates are firefox and gedit (or some other graphical text editor).

There's an issue with this though that needs to be solved (independently of the firefox issue).  $HOME in the noVNC container is set to /headless and is used by the noVNC container install process.  Thus, when users open a local terminal, $HOME is incorrect.  This should be fixed.

**Comment by brianmajor** [comment]
The $HOME issue:  https://github.com/opencadc/arcade/issues/40

**Comment by brianmajor** [comment]
Firefox has been moved to the noVNC container and $HOME has been corrected.  However, this locally installed version is crashing frequently too.  Details to follow.

**Comment by yeunga** [comment]
firefox crashes on some URLs, e.g. https://www.acm.org/publications

firefox also crashes more often when multiple tabs are used.

**Comment by drtobybrown** [comment]
Firefox still crashing often, even on just one tab, making it basically unusable.
